---
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
jackson:
  default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: "*"

message: This is NOT a default

spring: 
  cloud:
    services:
      registrationMethod: direct